---
- hosts: node
  tasks:
    - name: "Check if {{ node_home }}/data/platon directory exists"
      stat:
        path: "{{ node_home }}/data/platon"
      register: result

    - name: "Stop initializing when platon directory exists"
      fail:
        msg: "The {{ node_home }}/data/platon exists"
      when: result.stat.exists

    - name: "Sync genesis.json for {{ node_name }}"
      template:
        src: "/etc/ansible/files/platon/genesis.json"
        dest: "{{ node_home }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0644

    - name: "Initialize {{ node_name }}"
      shell: "{{ node_bin }} --datadir {{ node_home }}/data init {{ node_home }}/genesis.json"
