---
    - name: "Add the file '/etc/sysctl.d/99-optimize.conf' "
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/99-optimize.conf
        reload: yes
      with_items:
        - { name: 'net.ipv4.tcp_max_tw_buckets',  value: '6000' }
        - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000'}
#        - { name: 'net.ipv4.tcp_tw_recycle', value: '1' }
        - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
        - { name: 'net.ipv4.tcp_syncookies', value: '1' }
        - { name: 'net.core.somaxconn', value: '262144' }
        - { name: 'net.core.netdev_max_backlog', value: '262144' }
        - { name: 'net.ipv4.tcp_max_orphans', value: '262144' }
        - { name: 'net.ipv4.tcp_max_syn_backlog', value: '262144' }
        - { name: 'net.ipv4.tcp_timestamps', value: '0' }
        - { name: 'net.ipv4.tcp_synack_retries', value: '1' }
        - { name: 'net.ipv4.tcp_syn_retries', value: '1' }
        - { name: 'net.ipv4.tcp_fin_timeout', value: '1' }

    - name: "Add the file /etc/security/limits.d/optimize.conf"
      pam_limits:
        domain: '*'
        limit_type: "{{item.limit_type}}"
        limit_item: "{{item.limit_item}}"
        value: "{{item.value}}"
        dest: /etc/security/limits.d/optimize.conf
      with_items:
        - { limit_type: '-', limit_item: 'nofile', value: 65536 }
        - { limit_type: '-', limit_item: 'nproc', value: 65536 }
        - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
        - { limit_type: 'hard', limit_item: 'memlock', value: unlimited } 

    - name: "Create the file /etc/profile.d/history.sh"
      file:
        path: /etc/profile.d/history.sh
        state: touch
        mode: 0644
        owner: root
        group: root
    - name: "Add content to /etc/profile.d/history.sh"
      lineinfile: 
        dest: /etc/profile.d/history.sh
        line: 'HISTTIMEFORMAT="$USER %F %T "'


