---
- hosts: "{{ target }}"
  become: true
  vars_prompt:
    - name: "target"
      prompt: "Which host or group would you like to assign"
      private: no
      default: "Default: empty"
    - name: "file_name"
      prompt: "Which file would you like to upload"
      private: no
      default: "Default: empty"
  tasks:
    - name: "Install python-pip"
      package:
        name: python-pip
        state: present
      become: true

    - name: "Install pip dependences"
      pip:
        name: "{{ item }}"
      with_items:
        - qiniu
        - boto3
      become: true

    - name: "Upload to AWS S3"
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "{{ aws_bucket_name }}"
        src: "/tmp/{{ file_name }}"
        object: "/tmp/{{ file_name }}"
        mode: put
        permission: public-read
