redis_url: 10.165.1.101:6379,10.165.1.101:6380,10.165.1.102:6379,10.165.1.102:6380,10.165.1.103:6379,10.165.1.103:6380
redis_pass: UTDf5wx3jqRDv1ZE
scan_mysql_url: jdbc:mysql://rm-8faba9m8x9g784my6.mysql.germany.rds.aliyuncs.com:3306/platon_agent?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
scan_mysql_db: platon_agent
scan_mysql_user: ENC(MDhOMDP+5tNjCohnTTC0hB5+Bbf5uw2X)
scan_mysql_pass: ENC(ZWNEYjEfJ5T8xZNwaY85VdZp3Emgt8yXt7kVNzB0RWo=)
web3j_addresses: 10.165.1.104:6788
es_nodes: 10.165.1.101,10.165.1.102,10.165.1.103
es_port: 9200
es_name: es-backup
