---
- hosts: "{{ target }}"
  become: true
  vars_prompt:
    - name: "target"
      prompt: "Which host or group would you like to assign"
      private: no
      default: "Default: empty"
  tasks:
    - name: "Delete data/producer directory"
      become: yes
      file:
          path: "{{ app_home }}/eosio/data/producer"
          state: absent
    - name: "Delete data/generator directory"
      become: yes
      file:
          path: "{{ app_home }}/eosio/data/generator"
          state: absent

    - name: "Create data/producer directory"
      file:
          path: "{{ app_home }}/eosio/data/producer"
          owner: pchuant
          group: pchuant
          mode: 0755
          state: directory
    - name: "Create data/generator directory"
      file:
          path: "{{ app_home }}/eosio/data/generator"
          owner: pchuant
          group: pchuant
          mode: 0755
          state: directory
