---
- hosts: "{{ target }}"
  become: true
  vars_prompt:
    - name: "target"
      prompt: "Which host or group would you like to assign"
      private: no
      default: "Default: empty"
  tasks:
    - name: "Unarchive foundation data on the remote machine"
      unarchive:
        src: "{{ app_home }}/eosio.tar.gz"
        dest: "{{ app_home }}"
        remote_src: yes
        group: pchuant
        owner: pchuant
