---
- hosts: "{{ target }}"
  vars_prompt:
    - name: "target"
      prompt: "Which host or group would you like to assign"
      private: no
      default: "Default: empty"
  tasks:
    - name: "start generator"
      shell: "{{ node_home }}/bin/start_generator.sh"
